version: '3'

services:
   nginx:
      image: nginx
      volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./front-end:/var/www/front-end
      ports:
         - "80:80"

   back-end:
      image: flask-api
      volumes:
         - ./back-end/.env:/flask-api/.env
      expose:
         - "5000"
