version: '3'

services:
   nginx:
      image: nginx
      volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./front-end:/var/www/front-end
      ports:
         - "80:80"

   back-end:
      image: guruprasadkannan/flask-api:1.0
      volumes:
         - ./back-end/.env:/guruprasadkannan/flask-api:1.0/.env
      expose:
         - "5000"
